version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://db:5432/postgres
      JDBC_DATABASE_URL: postgresql://db:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

    command: mvn spring-boot:run
    volumes:
      - .:/app
      - maven_repository:/root/.m2

  db:
    image: "postgres:13-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
    driver: local
  maven_repository:
    driver: local